from __future__ import annotations

import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from helpers import MOCK_ROUTES, REPO, Sandbox  # noqa: E402

import unittest  # noqa: E402

from agent_on.docs import render_routes_doc  # noqa: E402
from agent_on.invariants import build_context, evaluate  # noqa: E402
from agent_on.schemas.routes import load_routes  # noqa: E402

BASE = "http://127.0.0.1:1"


def one(paths, ident):
    return next(r for r in evaluate(build_context(paths), ids=[ident]))


class RenderTest(unittest.TestCase):
    def test_render_is_deterministic_and_names_every_source_and_route(self):
        with Sandbox(MOCK_ROUTES.format(base=BASE)) as sb:
            table = load_routes(sb.paths)
            text = render_routes_doc(table)
            self.assertEqual(text, render_routes_doc(table))
            self.assertTrue(text.startswith("<!-- generated by scripts/routes-doc.py from routes.toml — do not edit -->\n# Routes\n"))
            for s in table.sources:
                self.assertIn(f"### {s}", text)
            for r in table.routes.values():
                self.assertIn(f"`{r.name}`", text)
                for a in r.aliases:
                    self.assertIn(f"`{a}`", text)
            self.assertIn("| free |", text)                                              # a keyless source's routes are free

    def test_the_real_page_is_current_and_the_invariant_sees_staleness(self):
        real = (REPO / "docs" / "ROUTES.md").read_text(encoding="utf-8")
        self.assertEqual(real, render_routes_doc(load_routes(__import__("agent_on.paths", fromlist=["default_paths"]).default_paths({"HOME": str(REPO), "AGENT_ON_CHECKOUT": str(REPO)}))))
        with Sandbox(MOCK_ROUTES.format(base=BASE), tree=None) as sb:
            self.assertEqual(one(sb.paths, "docs.current").result, "skip")                  # no page in the sandbox tree
            (sb.paths.checkout / "docs").mkdir()
            (sb.paths.checkout / "docs" / "ROUTES.md").write_text("stale\n", encoding="utf-8")
            r = one(sb.paths, "docs.current")
            self.assertEqual(r.result, "fail")
            self.assertIn("routes-doc.py", r.reason)
            (sb.paths.checkout / "docs" / "ROUTES.md").write_text(render_routes_doc(load_routes(sb.paths)), encoding="utf-8")
            self.assertEqual(one(sb.paths, "docs.current").result, "pass")

    def test_the_script_checks_and_writes(self):
        with Sandbox(MOCK_ROUTES.format(base=BASE)) as sb:
            (sb.paths.checkout / "docs").mkdir()
            env = {"PATH": "/usr/bin:/bin", "HOME": str(sb.paths.home), "AGENT_ON_CHECKOUT": str(sb.paths.checkout), "PYTHONPATH": str(REPO)}
            p = subprocess.run([sys.executable, str(REPO / "scripts" / "routes-doc.py"), "--check"], capture_output=True, text=True, env=env)
            self.assertEqual(p.returncode, 1, p.stderr)
            p = subprocess.run([sys.executable, str(REPO / "scripts" / "routes-doc.py")], capture_output=True, text=True, env=env)
            self.assertEqual(p.returncode, 0, p.stderr)
            self.assertTrue((sb.paths.checkout / "docs" / "ROUTES.md").exists())
            p = subprocess.run([sys.executable, str(REPO / "scripts" / "routes-doc.py"), "--check"], capture_output=True, text=True, env=env)
            self.assertEqual(p.returncode, 0, p.stderr)


if __name__ == "__main__":
    unittest.main()
