"""docs/ROUTES.md from routes.toml (§14 row D, §17): a pure function of L1, so the page can be checked (docs.current)."""
from __future__ import annotations

from .schemas.routes import Limits, Route, RouteTable, display_family

HEADER = "<!-- generated by scripts/routes-doc.py from routes.toml — do not edit -->\n# Routes\n"


def _lim(l: Limits | None) -> str:
    if l is None:
        return "—"
    return f"{l.input or '?'} / {l.output or '?'} ({l.confidence})"


def _price(r: Route, billing: str) -> str:
    if r.price is None:
        return "free" if billing == "free" else "?"
    p = r.price.per_mtok()
    return f"${p['input']} / ${p['output']} per Mtok"


def _reasoning(r: Route) -> str:
    if r.reasoning is None:
        return "—"
    return ("supported" if r.reasoning.supported else "no") + (f" ({', '.join(r.reasoning.efforts)})" if r.reasoning.efforts else "")


def render_routes_doc(table: RouteTable) -> str:
    """L1 only: packaged routes from routes.toml. Discovered routes (routes.discovered.toml) are state, not
    declarations, and never appear here — `agent-on status` is where they're seen (fix-round-1 ruling: the
    page must not depend on $STATE, or docs.current would fail on a machine with a nonempty discovered file)."""
    out = [HEADER, "", "Declared in `routes.toml` (L1). Measured values — served, limits verified, cost model, qualification — are in",
           "`agent-on status`, never here. Discovered routes (from `$STATE/routes.discovered.toml`) are state, not",
           "declarations — `agent-on status` shows them.", "", "## Sources", "",
           "| source | backend | available | base_url | auth_env | billing | catalog | discover | limits in / out |", "|---|---|---|---|---|---|---|---|---|"]
    for name, s in sorted(table.sources.items()):
        out.append(f"| `{name}` | {s.backend} | {'yes' if s.available else 'host config required'} | {s.base_url or '—'} | {s.auth_env or 'none'} | {s.billing} | {s.catalog or '—'} | {'yes' if s.discover else 'no'} | {_lim(s.limits)} |")
    out += ["", "## Routes", ""]
    for sname in sorted(table.sources):
        routes = sorted((r for r in table.by_source(sname) if r.packaged), key=lambda r: r.name)
        out += [f"### {sname}", "", "| route | full family | aliases | wire model | limits in / out | from | price | reasoning |", "|---|---|---|---|---|---|---|---|"]
        billing = table.sources[sname].billing
        for r in routes:
            lim = table.effective_limits(r)
            origin = "route" if r.limits is not None else ("source" if lim else "—")
            out.append(f"| `{r.name}` | {display_family(r.wire_model) or '—'} | {', '.join(f'`{a}`' for a in r.aliases) or '—'} | {r.wire_model} | {_lim(lim)} | {origin} | {_price(r, billing)} | {_reasoning(r)} |")
        if not routes:
            out.append("no packaged routes")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"
