"""docs/ROUTES.md from routes.toml (§14 row D, §17): a pure function of L1, so the page can be checked (docs.current)."""
from __future__ import annotations

from .schemas.routes import Limits, Route, RouteTable

HEADER = "<!-- generated by scripts/routes-doc.py from routes.toml — do not edit -->\n# Routes\n"


def _lim(l: Limits | None) -> str:
    if l is None:
        return "—"
    return f"{l.input or '?'} / {l.output or '?'} ({l.confidence})"


def _price(r: Route, keyless: bool) -> str:
    if r.price is None:
        return "free" if keyless else "?"
    p = r.price.per_mtok()
    return f"${p['input']} / ${p['output']} per Mtok"


def _reasoning(r: Route) -> str:
    if r.reasoning is None:
        return "—"
    return ("supported" if r.reasoning.supported else "no") + (f" ({', '.join(r.reasoning.efforts)})" if r.reasoning.efforts else "")


def render_routes_doc(table: RouteTable) -> str:
    out = [HEADER, "", "Declared in `routes.toml` (L1). Measured values — served, limits verified, cost model, qualification — are in",
           "`agent-on status`, never here.", "", "## Sources", "", "| source | base_url | auth_env | catalog | discover | limits in / out |", "|---|---|---|---|---|---|"]
    for name, s in sorted(table.sources.items()):
        out.append(f"| `{name}` | {s.base_url} | {s.auth_env or 'none'} | {s.catalog or '—'} | {'yes' if s.discover else 'no'} | {_lim(s.limits)} |")
    out += ["", "## Routes", ""]
    for sname in sorted(table.sources):
        routes = sorted(table.by_source(sname), key=lambda r: r.name)
        out += [f"### {sname}", "", "| route | aliases | wire model | limits in / out | from | price | reasoning | kind |", "|---|---|---|---|---|---|---|---|"]
        keyless = table.sources[sname].auth_env is None
        for r in routes:
            lim = table.effective_limits(r)
            origin = "route" if r.limits is not None else ("source" if lim else "—")
            out.append(f"| `{r.name}` | {', '.join(f'`{a}`' for a in r.aliases) or '—'} | {r.wire_model} | {_lim(lim)} | {origin} | {_price(r, keyless)} | {_reasoning(r)} | {'packaged' if r.packaged else 'discovered'} |")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"
